# generated by `cargo xtask gen nix-cargo-hashes` -- DO NOT EDIT.
{
	"serenity-0.12.5" = "sha256-SEuJbFx3f7/aMWZsU5lwUDuz5SoFGm9DTVhRVdA0AmU="; # 37b9f433ada8b9ccc5f93f04826403b175855f86
	"typesize-0.1.15" = "sha256-nr0KC+fphnZGocu2ORzG0uNen4DUExVfvNYijsM+8p4="; # 4e032bc507cc693d3f66aac905ed7df8473f9df7
}
