# generated by `cargo xtask gen nix-cargo-hashes` -- DO NOT EDIT.
{
	"serenity-0.12.5" = "sha256-Mb+LkDOLSyhpz70kopYhMO1r+PIpnqxXZKJ3j6sfvK4="; # 46f5689715c49476ab289465b675dd79e25fb079
	"typesize-0.1.15" = "sha256-nr0KC+fphnZGocu2ORzG0uNen4DUExVfvNYijsM+8p4="; # 4e032bc507cc693d3f66aac905ed7df8473f9df7
}
