[package]
name = "webpack_chunk_parser"
version = "0.1.0"
edition.workspace = true

[lib]
doctest = false

[dependencies]
oxc.workspace = true
ast_parser.workspace = true
derive_more.workspace = true
anyhow.workspace = true
serde.workspace = true
smol_str.workspace = true
memchr.workspace = true
regex.workspace = true
explorer_types.workspace = true

[dev-dependencies]
insta.workspace = true
itertools.workspace = true

[lints]
workspace = true
