/* eslint-disable @stylistic/lines-between-class-members */
/* eslint-disable @stylistic/max-len */
/* eslint-disable @stylistic/newline-per-chained-call */
/* eslint-disable simple-import-sort/imports */
/* eslint-disable unused-imports/no-unused-imports -- we import some types for reference from jsdoc */
// ***********************************************************
// This file is generated by scripts/codegen/vscExtSettings.ts
// Do not edit this file directly
// ***********************************************************
import { workspace, WorkspaceConfiguration, ConfigurationTarget } from "vscode";
export class _Settings {
    /**
     * the delay in ms bewteen diagnostic refreshes.
     * @default 1500
     * @see {@link workspace.getConfiguration}
     * @see {@link WorkspaceConfiguration.get}
     */
    public get diagnosticRefreshTimeout(): number {
        return workspace.getConfiguration("vencord-user-companion").get<number>("diagnosticRefreshTimeout", 1500);
    }
    /**
     * the delay in ms bewteen diagnostic refreshes.
     *
     * Sets the value of "diagnosticRefreshTimeout"
     *
     * @param value The new value to set
     * @see {@link workspace.getConfiguration}
     * @see {@link WorkspaceConfiguration.update}
     */
    public set diagnosticRefreshTimeout(value: number) {
        workspace.getConfiguration("vencord-user-companion").update("diagnosticRefreshTimeout", value);
    }
    /**
     * the delay in ms bewteen diagnostic refreshes.
     *
     * Sets the value of "diagnosticRefreshTimeout"
     *
     * @param value The new value to set
     * @see {@link workspace.getConfiguration}
     * @see {@link WorkspaceConfiguration.update}
     */
    public setDiagnosticRefreshTimeout(value: number, configurationTarget?: boolean | ConfigurationTarget | null, overrideInLanguage?: boolean): Thenable<void> {
        return workspace.getConfiguration("vencord-user-companion").update("diagnosticRefreshTimeout", value, configurationTarget, overrideInLanguage);
    }
    /**
     * Override path to the companion_lsp binary. Defaults to the bundled binary if unset. The env var COMPANION_LSP_BIN takes precedence over this setting.
     * @default
     * @see {@link workspace.getConfiguration}
     * @see {@link WorkspaceConfiguration.get}
     */
    public get lspPath(): string {
        return workspace.getConfiguration("vencord-user-companion").get<string>("lspPath", "");
    }
    /**
     * Override path to the companion_lsp binary. Defaults to the bundled binary if unset. The env var COMPANION_LSP_BIN takes precedence over this setting.
     *
     * Sets the value of "lspPath"
     *
     * @param value The new value to set
     * @see {@link workspace.getConfiguration}
     * @see {@link WorkspaceConfiguration.update}
     */
    public set lspPath(value: string) {
        workspace.getConfiguration("vencord-user-companion").update("lspPath", value);
    }
    /**
     * Override path to the companion_lsp binary. Defaults to the bundled binary if unset. The env var COMPANION_LSP_BIN takes precedence over this setting.
     *
     * Sets the value of "lspPath"
     *
     * @param value The new value to set
     * @see {@link workspace.getConfiguration}
     * @see {@link WorkspaceConfiguration.update}
     */
    public setLspPath(value: string, configurationTarget?: boolean | ConfigurationTarget | null, overrideInLanguage?: boolean): Thenable<void> {
        return workspace.getConfiguration("vencord-user-companion").update("lspPath", value, configurationTarget, overrideInLanguage);
    }
    /**
     * Log level for the companion_lsp server (sets COMPANION_LSP_LOG). Changing this restarts the server. Use the "Vencord Companion: Set Log Level" command for a quick picker.
     * @default info
     * @see {@link workspace.getConfiguration}
     * @see {@link WorkspaceConfiguration.get}
     */
    public get logLevel(): "trace" | "debug" | "info" | "warn" | "error" | "off" {
        return workspace.getConfiguration("vencord-user-companion").get<"trace" | "debug" | "info" | "warn" | "error" | "off">("logLevel", "info");
    }
    /**
     * Log level for the companion_lsp server (sets COMPANION_LSP_LOG). Changing this restarts the server. Use the "Vencord Companion: Set Log Level" command for a quick picker.
     *
     * Sets the value of "logLevel"
     *
     * @param value The new value to set
     * @see {@link workspace.getConfiguration}
     * @see {@link WorkspaceConfiguration.update}
     */
    public set logLevel(value: "trace" | "debug" | "info" | "warn" | "error" | "off") {
        workspace.getConfiguration("vencord-user-companion").update("logLevel", value);
    }
    /**
     * Log level for the companion_lsp server (sets COMPANION_LSP_LOG). Changing this restarts the server. Use the "Vencord Companion: Set Log Level" command for a quick picker.
     *
     * Sets the value of "logLevel"
     *
     * @param value The new value to set
     * @see {@link workspace.getConfiguration}
     * @see {@link WorkspaceConfiguration.update}
     */
    public setLogLevel(value: "trace" | "debug" | "info" | "warn" | "error" | "off", configurationTarget?: boolean | ConfigurationTarget | null, overrideInLanguage?: boolean): Thenable<void> {
        return workspace.getConfiguration("vencord-user-companion").update("logLevel", value, configurationTarget, overrideInLanguage);
    }
}
export const Settings = new _Settings(); /* eslint-enable @stylistic/lines-between-class-members */
/* eslint-enable @stylistic/max-len */
/* eslint-enable @stylistic/newline-per-chained-call */
/* eslint-enable simple-import-sort/imports */
/* eslint-enable unused-imports/no-unused-imports -- we import some types for reference from jsdoc */
