packages: []

ignoredBuiltDependencies:
  - core-js

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - less
  - netlify-cli
  - sharp
  - unix-dgram
  - workerd

overrides:
  vite: npm:rolldown-vite@latest

patchedDependencies:
  '@tanstack/start-plugin-core': patches/@tanstack__start-plugin-core.patch
  typescript: patches/typescript.patch
