packages: []

ignoredBuiltDependencies:
  - core-js

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - less
  - netlify-cli
  - sharp
  - unix-dgram
  - workerd

patchedDependencies:
  '@tanstack/start-plugin-core': patches/@tanstack__start-plugin-core.patch
  eslint-plugin-react-x: patches/eslint-plugin-react-x.patch
  typescript: patches/typescript.patch

verifyDepsBeforeRun: install
