/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class ProcessingBuild {
  constructor()
  set metadata(metadata: ProcessingMetadata)
  set depInfo(depInfo: ProcessingDepInfo)
  setModuleSources(chunkName: string, moduleIds: Array<TModuleId>): void
  setSource(moduleId: TModuleId, source: string): void
  write(): void
}

export declare class ProcessingDepInfo {
  constructor()
  set keyModules(keyModules: ProcessingKeyModules)
  addSyncDep(moduleId: TModuleId, syncUseId: TModuleId): void
  addLazyDep(moduleId: TModuleId, lazyUseId: TModuleId): void
}

export declare class ProcessingKeyModules {
  constructor()
  addFluxDispatcherClass(moduleId: TModuleId, exportName: ProcessingExportName): void
}

export declare class ProcessingMetadata {
  constructor()
  set buildHash(buildHash: string)
  set buildNumber(buildNumber: number)
  setFirstSeen(firstSeen: number): void
  set entryPoint(entryPoint: TModuleId | undefined | null)
  set envVarText(envVarText: string)
}

export declare const enum Channel {
  Stable = 0,
  Canary = 1
}

export interface HandleBuildOpts {
  buildHash: string
  html: string
  channel: Channel
}

export type ProcessingExportName =
  | { type: 'Named', field0: string }
  | { type: 'Default' }

export declare function start(handleBuild: ((arg: HandleBuildOpts) => void)): Promise<void>
