use crate::{Runnable, util::cmd::resolve_program_in_path};
use anyhow::{Context, Result, bail};
use clap::Args;
use serde::Deserialize;
use std::{
	collections::{BTreeMap, BTreeSet},
	fmt::Write as _,
	fs,
	process,
};
use tracing::{info, warn};

#[derive(Args, Clone, Debug)]
pub struct Command {
	/// Re-fetch every git dependency, even ones whose revision is unchanged
	#[arg(long)]
	force: bool,
}

const LOCK_PATH: &str = "Cargo.lock";
const OUT_PATH: &str = "nix/cargo-output-hashes.nix";

#[derive(Deserialize)]
struct Lock {
	#[serde(default)]
	package: Vec<Package>,
}

#[derive(Deserialize)]
struct Package {
	name: String,
	version: String,
	source: Option<String>,
}

/// A git dependency, as identified by the revision it is locked to.
struct GitDep {
	url: String,
	rev: String,
	/// Every `<name>-<version>` in the lockfile that resolves to this
	/// revision. nixpkgs maps the keys of `outputHashes` to git revisions, so
	/// only one of these needs an entry.
	packages: BTreeSet<String>,
}

#[derive(Deserialize)]
struct PrefetchOutput {
	hash: String,
}

/// Parse the `git+<url>[?<type>=<value>]#<rev>` source of a lockfile entry.
fn parse_git_source(source: &str) -> Option<(&str, &str)> {
	let source = source.strip_prefix("git+")?;
	let (url, rev) = source.split_once('#')?;
	let url = url
		.split_once('?')
		.map_or(url, |(url, _query)| url);
	Some((url, rev))
}

fn git_deps() -> Result<Vec<GitDep>> {
	let raw_lock = fs::read_to_string(LOCK_PATH)
		.with_context(|| format!("Failed to read {LOCK_PATH}"))?;
	let lock: Lock = toml::from_str(&raw_lock)
		.with_context(|| format!("Failed to parse {LOCK_PATH}"))?;
	let mut deps: BTreeMap<String, GitDep> = BTreeMap::new();
	for pkg in &lock.package {
		let Some((url, rev)) = pkg
			.source
			.as_deref()
			.and_then(parse_git_source)
		else {
			continue;
		};
		deps.entry(rev.to_string())
			.or_insert_with(|| GitDep {
				url: url.to_string(),
				rev: rev.to_string(),
				packages: BTreeSet::new(),
			})
			.packages
			.insert(format!("{}-{}", pkg.name, pkg.version));
	}
	Ok(deps.into_values().collect())
}

/// Read the hashes already recorded in [`OUT_PATH`], keyed by git revision.
fn existing_hashes() -> BTreeMap<String, String> {
	let Ok(contents) = fs::read_to_string(OUT_PATH) else {
		return BTreeMap::new();
	};
	contents
		.lines()
		.filter_map(|line| {
			// "<name>-<version>" = "<hash>"; # <rev>
			let (entry, rev) = line.split_once("; # ")?;
			let hash = entry
				.rsplit_once("= \"")?
				.1
				.strip_suffix('"')?;
			Some((rev.trim().to_string(), hash.to_string()))
		})
		.collect()
}

fn nix_prefetch_git() -> Result<process::Command> {
	if let Ok(path) = resolve_program_in_path("nix-prefetch-git") {
		return Ok(process::Command::new(path));
	}
	warn!(
		"nix-prefetch-git not found in PATH, falling back to `nix run nixpkgs#nix-prefetch-git`"
	);
	let nix = resolve_program_in_path("nix")
		.context("Failed to find nix-prefetch-git or nix in PATH")?;
	let mut cmd = process::Command::new(nix);
	cmd.args(["run", "nixpkgs#nix-prefetch-git", "--"]);
	Ok(cmd)
}

fn prefetch(dep: &GitDep) -> Result<String> {
	info!("Fetching {} at {}", dep.url, dep.rev);
	let output = nix_prefetch_git()?
		.args(["--quiet", "--url", &dep.url, "--rev", &dep.rev])
		.output()
		.with_context(|| {
			format!("Failed to run nix-prefetch-git for {}", dep.url)
		})?;
	if !output.status.success() {
		bail!(
			"nix-prefetch-git failed for {} at {} with status {}:\n{}",
			dep.url,
			dep.rev,
			output.status,
			String::from_utf8_lossy(&output.stderr)
		);
	}
	let parsed: PrefetchOutput = serde_json::from_slice(&output.stdout)
		.with_context(|| {
			format!("Failed to parse nix-prefetch-git output for {}", dep.url)
		})?;
	Ok(parsed.hash)
}

impl Runnable for Command {
	fn run(&self) -> Result<()> {
		let deps = git_deps()?;
		if deps.is_empty() {
			info!("No git dependencies in {LOCK_PATH}");
		}
		let known = if self.force {
			BTreeMap::new()
		} else {
			existing_hashes()
		};
		let mut out = String::from(
			"# generated by `cargo xtask gen nix-cargo-hashes` -- DO NOT EDIT.\n\
			 {\n",
		);
		for dep in &deps {
			let hash = match known.get(&dep.rev) {
				Some(hash) => {
					info!("Reusing hash for {} at {}", dep.url, dep.rev);
					hash.clone()
				}
				None => prefetch(dep)?,
			};
			let key = dep
				.packages
				.first()
				.expect("every dep has at least one package");
			writeln!(out, "\t\"{key}\" = \"{hash}\"; # {}", dep.rev)
				.expect("writing to a String cannot fail");
		}
		out.push_str("}\n");
		fs::write(OUT_PATH, out)
			.with_context(|| format!("Failed to write {OUT_PATH}"))?;
		info!("Wrote {} hashes to {OUT_PATH}", deps.len());
		Ok(())
	}
}
