use std::{
	fmt::Write as _,
	fs,
	io::{self, BufRead as _, Write as _},
	process,
};

use anyhow::{Context, Result};
use clap::Args;
use serde::Deserialize;
use tracing::info;

use crate::{
	Runnable,
	util::{cmd::CommandExt, nvim::PluginDir},
};

#[derive(Args, Clone, Debug)]
pub struct Command {
	#[command(flatten)]
	pub plugin_dir: PluginDir,
}

/// Where the command table lives, relative to the plugin checkout.
const OUT_REL_PATH: &str = "lua/vencord-companion/_generated/cmds.lua";

const HEADER: &str = "\
-- ***********************************************************
-- This file is generated by `cargo xtask gen nvim-commands`
-- Do not edit this file directly
-- ***********************************************************
";

/// One entry of the server's `CMD_MAP`, as the `get_cmds` example prints it.
#[derive(Deserialize, PartialEq, Eq, PartialOrd, Ord)]
#[serde(deny_unknown_fields)]
struct Cmd {
	command: String,
	title: String,
}

/// Quote `s` as a Lua string literal.
///
/// Command names and titles are plain ASCII today, but nothing enforces that,
/// and an unescaped quote would produce a file that does not parse.
fn lua_string(s: &str) -> String {
	let mut out = String::with_capacity(s.len() + 2);
	out.push('"');
	for c in s.chars() {
		match c {
			'"' => out.push_str("\\\""),
			'\\' => out.push_str("\\\\"),
			'\n' => out.push_str("\\n"),
			'\r' => out.push_str("\\r"),
			c => out.push(c),
		}
	}
	out.push('"');
	out
}

impl Command {
	/// Read the user-visible commands straight out of the server's `CMD_MAP`.
	fn read_cmds() -> Result<Vec<Cmd>> {
		let (out, out_writer) =
			io::pipe().context("creating pipe for get_cmds output")?;
		let mut child = process::Command::cargo("run")?
			.arg("--example")
			.arg("get_cmds")
			.stdout(out_writer)
			.spawn()
			.context("spawning get_cmds example")?;
		let mut cmds = Vec::new();
		for line in io::BufReader::new(out).lines() {
			let line = line.context("reading get_cmds output")?;
			cmds.push(
				serde_json::from_str(&line)
					.with_context(|| format!("deserializing cmd {line:?}"))?,
			);
		}
		let status = child
			.wait()
			.context("waiting for get_cmds example")?;
		anyhow::ensure!(status.success(), "get_cmds example failed: {status}");
		cmds.sort_unstable();
		Ok(cmds)
	}
}

impl Runnable for Command {
	fn run(&self) -> Result<()> {
		let cmds = Self::read_cmds()?;
		let mut out = String::from(HEADER);
		out.push_str("return {\n");
		for Cmd { command, title } in &cmds {
			// Titles are not prefixed with "Vencord Companion: " the way the
			// VS Code ones are: that prefix exists to disambiguate entries in
			// a flat command palette, and is noise under `:VencordCompanion`.
			writeln!(out, "\t{{").expect("writing to a String cannot fail");
			writeln!(out, "\t\tcommand = {},", lua_string(command))
				.expect("writing to a String cannot fail");
			writeln!(out, "\t\ttitle = {},", lua_string(title))
				.expect("writing to a String cannot fail");
			writeln!(out, "\t}},").expect("writing to a String cannot fail");
		}
		out.push_str("}\n");

		let out_path = self
			.plugin_dir
			.resolve()?
			.join(OUT_REL_PATH);
		let dir = out_path
			.parent()
			.expect("out path has a parent");
		fs::create_dir_all(dir)
			.with_context(|| format!("creating {}", dir.display()))?;
		let mut file = fs::File::create(&out_path)
			.with_context(|| format!("creating {}", out_path.display()))?;
		file.write_all(out.as_bytes())
			.with_context(|| format!("writing {}", out_path.display()))?;
		info!("Wrote {} commands to {}", cmds.len(), out_path.display());
		Ok(())
	}
}
