[package]
name = "explorer_server_core"
version = "0.1.0"
edition.workspace = true

[dependencies]
explorer_types.workspace = true 
anyhow.workspace = true
serde.workspace = true
rmp-serde.workspace = true
zstd = { workspace = true, features = ["zstdmt"] }

[dev-dependencies]
tempfile.workspace = true
serde_json.workspace = true
smol_str.workspace = true

[lints]
workspace = true
