[package]
name = "explorer_types"
version = "0.1.0"
edition.workspace = true

[lib]
test = false
doctest = false

[dependencies]
serde.workspace = true
derive_more.workspace = true
jiff.workspace = true
oxc_span.workspace = true
typesize.workspace = true
prost.workspace = true
thiserror.workspace = true

[build-dependencies]
prost-build.workspace = true
protoc-bin-vendored.workspace = true

[lints]
workspace = true
