//! Discord application (slash) command registration and dispatch.
//!
//! Slash support is layered on top of the existing clap-driven command tree:
//! registration introspects each command's clap parser to emit Discord option
//! schemas, and an incoming interaction is *lowered* back into the same
//! multicall token stream a prefix invocation would produce, so it flows
//! through [`CommandFramework::match_command_tokens`] and the normal executor
//! path with argument parsing, checks, and `FromArgMatches` all reused
//! unchanged.

use std::collections::HashMap;

use anyhow::{Context as _, Result, bail};
use clap::{Arg, ArgAction};
use serenity::all::{
	CommandInteraction,
	CommandOptionType,
	Context,
	CreateCommand,
	CreateCommandOption,
	CreateInteractionResponse,
	CreateInteractionResponseFollowup,
	CreateInteractionResponseMessage,
	ResolvedOption,
	ResolvedValue,
};
use tracing::{error, info, warn};

use super::{
	Availability,
	Command,
	CommandCtx,
	CommandFramework,
	Status,
	render_clap_error,
};

/// Maps a Rust argument type to the Discord option type it should register as.
///
/// Implemented for the types used in command argument structs; a
/// `#[derive(SlashArgs)]` on a clap parser struct reads each field's type
/// through this trait to build the command's native option schema. Types
/// without an impl fall back to a plain `String` option that clap re-parses.
pub trait SlashArg {
	/// The Discord option type presented to the user (e.g. a native user
	/// picker for [`UserArg`](crate::util::UserArg)).
	const KIND: CommandOptionType;
}

impl SlashArg for crate::util::UserArg {
	const KIND: CommandOptionType = CommandOptionType::User;
}
impl SlashArg for String {
	const KIND: CommandOptionType = CommandOptionType::String;
}
impl SlashArg for bool {
	const KIND: CommandOptionType = CommandOptionType::Boolean;
}
impl SlashArg for i64 {
	const KIND: CommandOptionType = CommandOptionType::Integer;
}
impl SlashArg for u64 {
	const KIND: CommandOptionType = CommandOptionType::Integer;
}
impl SlashArg for f64 {
	const KIND: CommandOptionType = CommandOptionType::Number;
}

/// The native Discord option kinds for a clap parser struct's fields, keyed by
/// argument name. Generated by `#[derive(SlashArgs)]`.
pub trait SlashSchema {
	/// `(arg_name, discord_kind)` for each field carrying a native type.
	fn slash_option_kinds() -> Vec<(&'static str, CommandOptionType)>;
}

/// A pointer to a [`SlashSchema::slash_option_kinds`] implementation, stored on
/// a [`Command`] when its arguments opt into native typing.
pub type SlashSchemaFn = fn() -> Vec<(&'static str, CommandOptionType)>;

/// Discord requires option/command descriptions to be 1–100 characters.
fn clamp_desc(desc: &str) -> String {
	const MAX: usize = 100;
	if desc.is_empty() {
		return "-".to_owned();
	}
	if desc.chars().count() <= MAX {
		return desc.to_owned();
	}
	desc.chars().take(MAX).collect()
}

/// clap injects `--help`/`--version` args; those are not real command options.
const fn is_meta_action(action: &ArgAction) -> bool {
	matches!(
		action,
		ArgAction::Help
			| ArgAction::HelpShort
			| ArgAction::HelpLong
			| ArgAction::Version
	)
}

/// The default Discord option type for a clap argument absent a native
/// override: booleans map to `Boolean`, everything else to a `String` that clap
/// re-parses at invocation.
fn default_kind(arg: &Arg) -> CommandOptionType {
	match arg.get_action() {
		ArgAction::SetTrue | ArgAction::SetFalse => CommandOptionType::Boolean,
		_ => CommandOptionType::String,
	}
}

/// Build the Discord options for a leaf command from its clap parser. clap
/// remains the source of truth for each option's name, description, and
/// requiredness; a native [`SlashSchema`] (when present) only overrides the
/// option *kind* so richer pickers (e.g. a user picker) are shown.
fn build_arg_options(node: &Command) -> Vec<CreateCommandOption> {
	let clap_cmd = node.parser.get(node);
	let native_kinds: HashMap<&str, CommandOptionType> = node
		.slash_schema
		.map(|schema| schema().into_iter().collect())
		.unwrap_or_default();
	let mut out = Vec::new();
	for arg in clap_cmd.get_arguments() {
		if is_meta_action(arg.get_action()) {
			continue;
		}
		let name = arg.get_id().as_str();
		let kind = native_kinds
			.get(name)
			.copied()
			.unwrap_or_else(|| default_kind(arg));
		let desc = arg
			.get_help()
			.map_or_else(|| name.to_owned(), ToString::to_string);
		let opt = CreateCommandOption::new(kind, name, clamp_desc(&desc))
			.required(arg.is_required_set());
		out.push(opt);
	}
	out
}

/// Build a second-level option (subcommand or subcommand-group) for a child of
/// a top-level command. Returns `None` when the node cannot be represented
/// (e.g. it would nest deeper than Discord's command→group→subcommand limit).
fn build_second_level(node: &Command) -> Option<CreateCommandOption> {
	let name = node.names[0];
	let desc = clamp_desc(node.desc.unwrap_or(name));
	if node.sub_cmds.is_empty() {
		let mut opt =
			CreateCommandOption::new(CommandOptionType::SubCommand, name, desc);
		for arg in build_arg_options(node) {
			opt = opt.add_sub_option(arg);
		}
		return Some(opt);
	}
	// a group: its children must all be leaf subcommands (the third and
	// deepest level Discord allows)
	let mut group = CreateCommandOption::new(
		CommandOptionType::SubCommandGroup,
		name,
		desc,
	);
	let mut any = false;
	for child in node.sub_cmds {
		if !child
			.availability
			.contains(Availability::SLASH)
		{
			continue;
		}
		if !child.sub_cmds.is_empty() {
			warn!(
				"slash: `{}` nests too deep for Discord (max \
				 command→group→subcommand); skipping",
				child.names[0]
			);
			continue;
		}
		let subname = child.names[0];
		let mut sub = CreateCommandOption::new(
			CommandOptionType::SubCommand,
			subname,
			clamp_desc(child.desc.unwrap_or(subname)),
		);
		for arg in build_arg_options(child) {
			sub = sub.add_sub_option(arg);
		}
		group = group.add_sub_option(sub);
		any = true;
	}
	any.then_some(group)
}

/// Build a top-level [`CreateCommand`] for a direct child of the root.
fn build_top_command(node: &Command) -> CreateCommand {
	let name = node.names[0];
	let mut cc = CreateCommand::new(name)
		.description(clamp_desc(node.desc.unwrap_or(name)));
	if node.sub_cmds.is_empty() {
		// leaf command: its clap args become options directly
		cc = cc.set_options(build_arg_options(node));
	} else {
		// a command that owns its own args *and* has subcommands cannot be
		// expressed in Discord (options and subcommands are mutually
		// exclusive), so only the subcommands are registered for slash
		for child in node.sub_cmds {
			if !child
				.availability
				.contains(Availability::SLASH)
			{
				continue;
			}
			if let Some(opt) = build_second_level(child) {
				cc = cc.add_option(opt);
			}
		}
	}
	cc
}

/// Convert a `ResolvedValue` into the string token clap should re-parse.
fn render_value(value: &ResolvedValue) -> Result<String> {
	Ok(match value {
		ResolvedValue::String(s) => (*s).to_owned(),
		ResolvedValue::Integer(i) => i.to_string(),
		ResolvedValue::Number(n) => n.to_string(),
		ResolvedValue::Boolean(b) => b.to_string(),
		ResolvedValue::User(user, _) => user.id.to_string(),
		ResolvedValue::Channel(channel) => channel.id.to_string(),
		ResolvedValue::Role(role) => role.id.to_string(),
		_ => bail!("unsupported slash option value type"),
	})
}

/// Render the leaf argument options of a command into clap tokens, emitting
/// them in the parser's declared argument order so positionals land in the
/// right slots. Boolean flags become bare `--flag` tokens (or nothing when
/// false); other options become `--long value` or a bare positional value.
pub(super) fn render_arg_tokens(
	clap_cmd: &clap::Command,
	provided: &HashMap<&str, ResolvedValue>,
) -> Result<Vec<String>> {
	let mut arg_tokens = Vec::new();
	for arg in clap_cmd.get_arguments() {
		if is_meta_action(arg.get_action()) {
			continue;
		}
		let Some(value) = provided.get(arg.get_id().as_str()) else {
			continue; // optional option the user omitted
		};
		if matches!(arg.get_action(), ArgAction::SetTrue | ArgAction::SetFalse)
		{
			if matches!(value, ResolvedValue::Boolean(true)) {
				arg_tokens.push(format!("--{}", arg.get_id()));
			}
			continue;
		}
		let rendered = render_value(value)?;
		if arg.is_positional() {
			arg_tokens.push(rendered);
		} else {
			let long = arg
				.get_long()
				.unwrap_or_else(|| arg.get_id().as_str());
			arg_tokens.push(format!("--{long}"));
			arg_tokens.push(rendered);
		}
	}
	Ok(arg_tokens)
}

/// Descend through subcommand / subcommand-group layers, pushing each layer's
/// name onto `path`, and return the leaf argument options.
fn descend<'a>(
	mut opts: Vec<ResolvedOption<'a>>,
	path: &mut Vec<String>,
) -> Vec<ResolvedOption<'a>> {
	while opts.len() == 1
		&& matches!(
			opts[0].value,
			ResolvedValue::SubCommand(_) | ResolvedValue::SubCommandGroup(_)
		) {
		let ResolvedOption { name, value, .. } = opts
			.pop()
			.expect("length checked above");
		path.push(name.to_owned());
		opts = match value {
			ResolvedValue::SubCommand(inner)
			| ResolvedValue::SubCommandGroup(inner) => inner,
			_ => unreachable!("matched as sub-command above"),
		};
	}
	opts
}

// the framework's core dispatch lives in `fw/mod.rs`; the slash-specific
// methods are grouped here in their own module
#[allow(clippy::multiple_inherent_impl)]
impl CommandFramework {
	/// Register the tree's slash commands with Discord. Called on `ready`.
	///
	/// When a guild is configured the command set is pushed to that guild
	/// (instant propagation). Globally, per poise's guidance, we do **not**
	/// auto-push on every boot (rate-limited, ~1h to propagate) — that is left
	/// to an explicit action.
	pub(super) async fn register_slash_commands(
		&self,
		ctx: &Context,
	) -> Result<()> {
		let commands = self.build_slash_commands();
		match self.guild {
			Some(guild) => {
				let count = commands.len();
				guild
					.set_commands(&ctx.http, commands)
					.await
					.context("failed to set guild slash commands")?;
				info!("Registered {count} slash command(s) to guild {guild}");
			}
			None => {
				info!(
					"No guild configured; skipping automatic global slash \
					 registration ({} command(s) built). Call \
					 `register_global_commands` to push globally.",
					commands.len()
				);
			}
		}
		Ok(())
	}

	/// Push the tree's slash commands globally. Overwrites the existing global
	/// set. Intended to be triggered explicitly (e.g. an owner command), not on
	/// every startup.
	pub async fn register_global_commands(&self, ctx: &Context) -> Result<()> {
		let commands = self.build_slash_commands();
		let count = commands.len();
		serenity::all::Command::set_global_commands(&ctx.http, commands)
			.await
			.context("failed to set global slash commands")?;
		info!("Registered {count} global slash command(s)");
		Ok(())
	}

	/// Build the Discord command set from the (slash-available) top-level nodes.
	pub(super) fn build_slash_commands(&self) -> Vec<CreateCommand> {
		self.root_cmd
			.sub_cmds
			.iter()
			.filter(|node| {
				node.availability
					.contains(Availability::SLASH)
			})
			.map(|node| build_top_command(node))
			.collect()
	}

	/// Resolve a command node by walking the tree along `path` (top-level name
	/// followed by any subcommand / group names).
	pub(super) fn resolve_node(&self, path: &[String]) -> Option<&Command> {
		let mut cur: &Command = self.root_cmd;
		for seg in path {
			cur = cur
				.sub_cmds
				.iter()
				.copied()
				.find(|c| c.names.iter().any(|n| *n == seg))?;
		}
		Some(cur)
	}

	/// Lower an interaction into the multicall token stream a prefix invocation
	/// would produce (`[top, sub.., --flag, value, positional..]`).
	fn tokens_for_interaction(
		&self,
		interaction: &CommandInteraction,
	) -> Result<Vec<String>> {
		let mut path = vec![interaction.data.name.clone()];
		let leaf_opts = descend(interaction.data.options(), &mut path);

		let Some(node) = self.resolve_node(&path) else {
			error!("Failed to resolve command node {:?}", &interaction.data);
			bail!("no command matches this interaction");
		};
		let clap_cmd = node.parser.get(node);

		let provided: HashMap<&str, ResolvedValue> = leaf_opts
			.into_iter()
			.map(|opt| (opt.name, opt.value))
			.collect();

		path.extend(render_arg_tokens(clap_cmd, &provided)?);
		Ok(path)
	}

	/// Resolve and run the command an interaction targets.
	async fn dispatch_interaction(
		&self,
		ctx: &Context,
		interaction: &CommandInteraction,
		cctx: &CommandCtx<'_>,
	) -> Result<()> {
		let tokens = self.tokens_for_interaction(interaction)?;
		let (cmd, args) = self.match_command_tokens(tokens)?;
		if !cmd
			.availability
			.contains(Availability::SLASH)
		{
			bail!("command is not available as a slash command");
		}
		if let Status::Fail(reason) = self.run_checks(ctx, cctx, cmd).await? {
			self.handle_check_failure(ctx, cctx, cmd, &reason)
				.await?;
			return Ok(());
		}
		cmd.executor
			.execute(ctx, cctx, cmd, self, &args)
			.await
			.with_context(|| {
				format!("Failed to execute command {}", cmd.names[0])
			})
	}

	/// Entry point from `EventHandler::interaction_create`: dispatch and, on
	/// failure, report the error back through the interaction.
	pub(super) async fn handle_interaction(
		&self,
		ctx: &Context,
		interaction: &CommandInteraction,
	) {
		let cctx = CommandCtx::Application { interaction };
		match self
			.dispatch_interaction(ctx, interaction, &cctx)
			.await
		{
			Ok(()) => info!("Executed slash command"),
			Err(e) => {
				let content =
					if let Some(clap_err) = e.downcast_ref::<clap::Error>() {
						let use_ansi = Self::should_use_ansi(ctx).await;
						render_clap_error(clap_err, use_ansi)
					} else {
						error!("Failed to execute slash command: {:?}", e);
						format!("command failed: {e}")
					};
				// the handler may already have responded; try an initial
				// response first, then fall back to a followup
				let initial = interaction
					.create_response(
						&ctx.http,
						CreateInteractionResponse::Message(
							CreateInteractionResponseMessage::new()
								.content(content.clone()),
						),
					)
					.await;
				if initial.is_err()
					&& let Err(e) = interaction
						.create_followup(
							&ctx.http,
							CreateInteractionResponseFollowup::new()
								.content(content),
						)
						.await
				{
					error!("Failed to send slash error response: {:?}", e);
				}
			}
		}
	}
}
