import type { Ref } from "react";

export const enum Language {
    PLAINTEXT,
    JSON,
    ABAP,
    APEX,
    AZCLI,
    BAT,
    BICEP,
    CAMELIGO,
    CLOJURE,
    COFFEESCRIPT,
    C,
    CPP,
    CSHARP,
    CSP,
    CSS,
    CYPHER,
    DART,
    DOCKERFILE,
    ECL,
    ELIXIR,
    FLOW9,
    FSHARP,
    FREEMARKER2,
    FREEMARKER2_TAG_ANGLE_INTERPOLATION_DOLLAR,
    FREEMARKER2_TAG_BRACKET_INTERPOLATION_DOLLAR,
    FREEMARKER2_TAG_ANGLE_INTERPOLATION_BRACKET,
    FREEMARKER2_TAG_BRACKET_INTERPOLATION_BRACKET,
    FREEMARKER2_TAG_AUTO_INTERPOLATION_DOLLAR,
    FREEMARKER2_TAG_AUTO_INTERPOLATION_BRACKET,
    GO,
    GRAPHQL,
    HANDLEBARS,
    HCL,
    HTML,
    INI,
    JAVA,
    JAVASCRIPT,
    JULIA,
    KOTLIN,
    LESS,
    LEXON,
    LUA,
    LIQUID,
    M3,
    MARKDOWN,
    MDX,
    MIPS,
    MSDAX,
    MYSQL,
    OBJECTIVE_C,
    PASCAL,
    PASCALIGO,
    PERL,
    PGSQL,
    PHP,
    PLA,
    POSTIATS,
    POWERQUERY,
    POWERSHELL,
    PROTO,
    PUG,
    PYTHON,
    QSHARP,
    R,
    RAZOR,
    REDIS,
    REDSHIFT,
    RESTRUCTUREDTEXT,
    RUBY,
    RUST,
    SB,
    SCALA,
    SCHEME,
    SCSS,
    SHELL,
    SOL,
    AES,
    SPARQL,
    SQL,
    ST,
    SWIFT,
    SYSTEMVERILOG,
    VERILOG,
    TCL,
    TWIG,
    TYPESCRIPT,
    TYPESPEC,
    VB,
    WGSL,
    XML,
    YAML,
    /**
     * Infer
     */
    UNKNOWN,
}

export interface CodeEditorProps<THandle> {
    initialCode?: string;
    onChange?(newCode: string): void;
    language?: Language;
    width?: string;
    height?: string;
    className?: string;
    ref?: Ref<THandle>;
}

