[package]
name = "pretty_printer"
description = "A rewrite of the pretty printer found in chrome's devtools, with byte-for-byte output (including bugs)."
version = "0.1.0"
edition.workspace = true
license = "BSD-3-Clause"

[dependencies]
anyhow.workspace = true
oxc.workspace = true
derive_more.workspace = true
regress.workspace = true
tracing.workspace = true

[dev-dependencies]
insta.workspace = true
macros.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
