[package]
name = "libsadancore"
version = "0.0.0"
publish = false
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen.workspace = true
anyhow.workspace = true

[dependencies.web-sys]
workspace = true
features = [
    "CanvasRenderingContext2d",
    "HtmlCanvasElement",
    "Document",
    "Window",
    "Element",
    "CssStyleDeclaration",
]

[lints]
workspace = true

[package.metadata.wasm-pack.profile.dev]
wasm-opt = ["-Oz"]

[package.metadata.wasm-pack.profile.profiling]
wasm-opt = ["-Oz"]

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-Oz"]
