[package]
name = "discord_scraper"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow.workspace = true
reqwest.workspace = true
reqwest-retry.workspace = true
reqwest-middleware.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
http.workspace = true
tracing.workspace = true
html_parser.workspace = true
regress.workspace = true
memchr.workspace = true
oxc_allocator = { workspace = true, features = ["pool"] }
const_format.workspace = true
webpack_chunk_parser.workspace = true
webpack_ast_parser.workspace = true
explorer_types.workspace = true
explorer_server_core.workspace = true
dashmap.workspace = true
bytes.workspace = true
miette_ctx.workspace = true
digest.workspace = true

[lints]
workspace = true
