[package]
name = "reporter"
version = "0.1.0"
edition.workspace = true

[dependencies]
tokio = { workspace = true, features = [
    "rt-multi-thread",
    "macros",
    "fs",
    "process",
] }
discord_scraper.workspace = true
explorer_types.workspace = true
explorer_server_core.workspace = true
vencord_ast_parser.workspace = true
anyhow.workspace = true
clap.workspace = true
clap_complete.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
zstd.workspace = true
serde.workspace = true
itertools.workspace = true
oxc.workspace = true
thiserror.workspace = true
regress.workspace = true
derive_more.workspace = true
oxc-miette = {workspace = true, features = ["fancy"]}
indicatif.workspace = true
owo-colors.workspace = true
unicode-width.workspace = true
textwrap.workspace = true
terminal_size.workspace = true
syntect = { workspace = true, features = ["regex-onig", "parsing"] }
bytes.workspace = true
oxc_allocator.workspace = true
reqwest-middleware.workspace = true
notify.workspace = true
rustc-hash.workspace = true
clearscreen.workspace = true
pretty_printer.workspace = true
bitcode.workspace = true

[dev-dependencies]
rmp-serde.workspace = true

[lints]
workspace = true
