[package]
name = "reporter"
version = "0.1.0"
edition.workspace = true

[dependencies]
tokio = { workspace = true, features = [
    "rt-multi-thread",
    "macros",
    "fs",
    "process",
] }
explorer_types.workspace = true
explorer_server_core.workspace = true
reqwest.workspace = true
anyhow.workspace = true
clap.workspace = true
clap_complete.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
zstd.workspace = true
rmp-serde.workspace = true
serde.workspace = true
itertools.workspace = true
tokio-stream = { workspace = true, features = ["fs"] }
tokio-util = { workspace = true }
oxc.workspace = true
oxc_ecmascript.workspace = true
oxc_traverse.workspace = true
thiserror.workspace = true
regress.workspace = true
xxhash-rust.workspace = true
derive_more.workspace = true
oxc-miette.workspace = true
indicatif.workspace = true
owo-colors = "4.3.0"
unicode-width = "0.2.2"
unicode-segmentation = "1.13.1"
textwrap = "0.16.2"
terminal_size = "0.4.4"
syntect = "5.3.0"
memchr = "2.8.0"
bitflags.workspace = true
num-bigint = "0.4"

[dev-dependencies]
insta.workspace = true

[lints]
workspace = true
