[package]
name = "vencord_ast_parser"
version = "0.1.0"
edition.workspace = true

[lib]
doctest = false

[dependencies]
anyhow.workspace = true
ast_parser.workspace = true
bitflags.workspace = true
derive_more.workspace = true
itertools.workspace = true
memchr.workspace = true
num-bigint.workspace = true
oxc = { workspace = true, features = ["minifier", "regular_expression"] }
oxc_span = { workspace = true, features = ["serialize"] }
oxc_ecmascript.workspace = true
oxc_traverse.workspace = true
regress.workspace = true
serde = { workspace = true, features = ["derive"] }
tracing.workspace = true
xxhash-rust.workspace = true
thiserror.workspace = true
smol_str.workspace = true
miette = { workspace = true }

[dev-dependencies]
insta.workspace = true
oxc = { workspace = true, features = ["minifier", "codegen"] }

[lints]
workspace = true
