[package]
name = "bot"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow.workspace = true
serenity = {workspace = true, features = ["default", "collector", "unstable", "typesize"]}
tokio.workspace = true
libc.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
futures-core.workspace = true
clap.workspace = true
bitflags.workspace = true
macros.workspace = true
shlex.workspace = true
itertools.workspace = true
derive_more.workspace = true
bot_config.workspace = true
serde_json.workspace = true
explorer_types.workspace = true
discord_scraper.workspace = true
smol_str.workspace = true
reporter.workspace = true
explorer_server_core.workspace = true
reqwest-middleware.workspace = true
async-scoped.workspace = true
memchr.workspace = true
rayon.workspace = true
oxc-miette.workspace = true
git2.workspace = true
qalc.workspace = true
qalc_sbox.workspace = true
cxx.workspace = true
git_hash.workspace = true
demangler.workspace = true
zxcvbn.workspace = true
sha1.workspace = true
arrayvec.workspace = true
serde.workspace = true
tempfile.workspace = true
thiserror.workspace = true
typesize.workspace = true
swift-demangler.workspace = true
skia-safe.workspace = true
bytes.workspace = true
gif.workspace = true
mini-moka.workspace = true
url.workspace = true

[lints]
workspace = true
