/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as RouteImport } from "./routes/_";
import { Route as EIndexRouteImport } from "./routes/e/index";
import { Route as AstViewerIndexRouteImport } from "./routes/ast-viewer/index";
import { Route as IndexRouteImport } from "./routes/_/index";
import { Route as EGuh123RouteImport } from "./routes/e/guh123";
import { Route as MinkyRouteImport } from "./routes/_/minky";
import { Route as DemanglerRouteImport } from "./routes/_/demangler";
import { Route as ComponentsRouteImport } from "./routes/_/components";
import { Route as VisIndexRouteImport } from "./routes/_/vis/index";
import { Route as DiscordIntlIndexRouteImport } from "./routes/_/discord-intl/index";
import { Route as R88x31IndexRouteImport } from "./routes/_/88x31/index";
import { Route as R88x31LangRouteImport } from "./routes/_/88x31/$lang";

const Route = RouteImport.update({
  id: "/_",
  getParentRoute: () => rootRouteImport,
} as any);
const EIndexRoute = EIndexRouteImport.update({
  id: "/e/",
  path: "/e/",
  getParentRoute: () => rootRouteImport,
} as any);
const AstViewerIndexRoute = AstViewerIndexRouteImport.update({
  id: "/ast-viewer/",
  path: "/ast-viewer/",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => Route,
} as any);
const EGuh123Route = EGuh123RouteImport.update({
  id: "/e/guh123",
  path: "/e/guh123",
  getParentRoute: () => rootRouteImport,
} as any);
const MinkyRoute = MinkyRouteImport.update({
  id: "/minky",
  path: "/minky",
  getParentRoute: () => Route,
} as any);
const DemanglerRoute = DemanglerRouteImport.update({
  id: "/demangler",
  path: "/demangler",
  getParentRoute: () => Route,
} as any);
const ComponentsRoute = ComponentsRouteImport.update({
  id: "/components",
  path: "/components",
  getParentRoute: () => Route,
} as any);
const VisIndexRoute = VisIndexRouteImport.update({
  id: "/vis/",
  path: "/vis/",
  getParentRoute: () => Route,
} as any);
const DiscordIntlIndexRoute = DiscordIntlIndexRouteImport.update({
  id: "/discord-intl/",
  path: "/discord-intl/",
  getParentRoute: () => Route,
} as any);
const R88x31IndexRoute = R88x31IndexRouteImport.update({
  id: "/88x31/",
  path: "/88x31/",
  getParentRoute: () => Route,
} as any);
const R88x31LangRoute = R88x31LangRouteImport.update({
  id: "/88x31/$lang",
  path: "/88x31/$lang",
  getParentRoute: () => Route,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/components": typeof ComponentsRoute;
  "/demangler": typeof DemanglerRoute;
  "/minky": typeof MinkyRoute;
  "/e/guh123": typeof EGuh123Route;
  "/ast-viewer/": typeof AstViewerIndexRoute;
  "/e/": typeof EIndexRoute;
  "/88x31/$lang": typeof R88x31LangRoute;
  "/88x31/": typeof R88x31IndexRoute;
  "/discord-intl/": typeof DiscordIntlIndexRoute;
  "/vis/": typeof VisIndexRoute;
}
export interface FileRoutesByTo {
  "/components": typeof ComponentsRoute;
  "/demangler": typeof DemanglerRoute;
  "/minky": typeof MinkyRoute;
  "/e/guh123": typeof EGuh123Route;
  "/": typeof IndexRoute;
  "/ast-viewer": typeof AstViewerIndexRoute;
  "/e": typeof EIndexRoute;
  "/88x31/$lang": typeof R88x31LangRoute;
  "/88x31": typeof R88x31IndexRoute;
  "/discord-intl": typeof DiscordIntlIndexRoute;
  "/vis": typeof VisIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_": typeof RouteWithChildren;
  "/_/components": typeof ComponentsRoute;
  "/_/demangler": typeof DemanglerRoute;
  "/_/minky": typeof MinkyRoute;
  "/e/guh123": typeof EGuh123Route;
  "/_/": typeof IndexRoute;
  "/ast-viewer/": typeof AstViewerIndexRoute;
  "/e/": typeof EIndexRoute;
  "/_/88x31/$lang": typeof R88x31LangRoute;
  "/_/88x31/": typeof R88x31IndexRoute;
  "/_/discord-intl/": typeof DiscordIntlIndexRoute;
  "/_/vis/": typeof VisIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/components"
    | "/demangler"
    | "/minky"
    | "/e/guh123"
    | "/ast-viewer/"
    | "/e/"
    | "/88x31/$lang"
    | "/88x31/"
    | "/discord-intl/"
    | "/vis/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/components"
    | "/demangler"
    | "/minky"
    | "/e/guh123"
    | "/"
    | "/ast-viewer"
    | "/e"
    | "/88x31/$lang"
    | "/88x31"
    | "/discord-intl"
    | "/vis";
  id:
    | "__root__"
    | "/_"
    | "/_/components"
    | "/_/demangler"
    | "/_/minky"
    | "/e/guh123"
    | "/_/"
    | "/ast-viewer/"
    | "/e/"
    | "/_/88x31/$lang"
    | "/_/88x31/"
    | "/_/discord-intl/"
    | "/_/vis/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  Route: typeof RouteWithChildren;
  EGuh123Route: typeof EGuh123Route;
  AstViewerIndexRoute: typeof AstViewerIndexRoute;
  EIndexRoute: typeof EIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_": {
      id: "/_";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof RouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/e/": {
      id: "/e/";
      path: "/e";
      fullPath: "/e/";
      preLoaderRoute: typeof EIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/ast-viewer/": {
      id: "/ast-viewer/";
      path: "/ast-viewer";
      fullPath: "/ast-viewer/";
      preLoaderRoute: typeof AstViewerIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_/": {
      id: "/_/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof Route;
    };
    "/e/guh123": {
      id: "/e/guh123";
      path: "/e/guh123";
      fullPath: "/e/guh123";
      preLoaderRoute: typeof EGuh123RouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_/minky": {
      id: "/_/minky";
      path: "/minky";
      fullPath: "/minky";
      preLoaderRoute: typeof MinkyRouteImport;
      parentRoute: typeof Route;
    };
    "/_/demangler": {
      id: "/_/demangler";
      path: "/demangler";
      fullPath: "/demangler";
      preLoaderRoute: typeof DemanglerRouteImport;
      parentRoute: typeof Route;
    };
    "/_/components": {
      id: "/_/components";
      path: "/components";
      fullPath: "/components";
      preLoaderRoute: typeof ComponentsRouteImport;
      parentRoute: typeof Route;
    };
    "/_/vis/": {
      id: "/_/vis/";
      path: "/vis";
      fullPath: "/vis/";
      preLoaderRoute: typeof VisIndexRouteImport;
      parentRoute: typeof Route;
    };
    "/_/discord-intl/": {
      id: "/_/discord-intl/";
      path: "/discord-intl";
      fullPath: "/discord-intl/";
      preLoaderRoute: typeof DiscordIntlIndexRouteImport;
      parentRoute: typeof Route;
    };
    "/_/88x31/": {
      id: "/_/88x31/";
      path: "/88x31";
      fullPath: "/88x31/";
      preLoaderRoute: typeof R88x31IndexRouteImport;
      parentRoute: typeof Route;
    };
    "/_/88x31/$lang": {
      id: "/_/88x31/$lang";
      path: "/88x31/$lang";
      fullPath: "/88x31/$lang";
      preLoaderRoute: typeof R88x31LangRouteImport;
      parentRoute: typeof Route;
    };
  }
}

interface RouteChildren {
  ComponentsRoute: typeof ComponentsRoute;
  DemanglerRoute: typeof DemanglerRoute;
  MinkyRoute: typeof MinkyRoute;
  IndexRoute: typeof IndexRoute;
  R88x31LangRoute: typeof R88x31LangRoute;
  R88x31IndexRoute: typeof R88x31IndexRoute;
  DiscordIntlIndexRoute: typeof DiscordIntlIndexRoute;
  VisIndexRoute: typeof VisIndexRoute;
}

const RouteChildren: RouteChildren = {
  ComponentsRoute: ComponentsRoute,
  DemanglerRoute: DemanglerRoute,
  MinkyRoute: MinkyRoute,
  IndexRoute: IndexRoute,
  R88x31LangRoute: R88x31LangRoute,
  R88x31IndexRoute: R88x31IndexRoute,
  DiscordIntlIndexRoute: DiscordIntlIndexRoute,
  VisIndexRoute: VisIndexRoute,
};

const RouteWithChildren = Route._addFileChildren(RouteChildren);

const rootRouteChildren: RootRouteChildren = {
  Route: RouteWithChildren,
  EGuh123Route: EGuh123Route,
  AstViewerIndexRoute: AstViewerIndexRoute,
  EIndexRoute: EIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
