export enum TextmateTheme {
    TOKYO_NIGHT,
    ROSE_PINE,
    ROSE_PINE_DAWN,
    ROSE_PINE_MOON,
    NORD,
    CATPPUCCIN_MOCHA,
    CATPPUCCIN_FRAPPE,
    CATPPUCCIN_MACCHIATO,
    CATPPUCCIN_LATTE,
    DRACULA,
    CATPPUCCIN = CATPPUCCIN_MOCHA,
}
