export enum TextmateTheme {
    TOKYO_NIGHT,
    ROSE_PINE,
    ROSE_PINE_DAWN,
    ROSE_PINE_MOON,
    NORD,
    CATPUCCIN_MOCHA,
    CATPUCCIN_FRAPPE,
    CATPUCCIN_MACCHIATO,
    CATPUCCIN_LATTE,
    DRACULA,
    CATPUCCIN = CATPUCCIN_MOCHA,
}
