import { dedent } from "@/utils/string";
import { Language, languageDisplayNames } from "@/utils/textmate/language";

import { mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import type { LanguageRegistration } from "shiki";

const grammars: Record<Language, null | (() => Promise<LanguageRegistration>)> = {
    async [Language.JSON]() {
        const json = await import("@shikijs/langs/json");

        return json.default[0];
    },
    async [Language.JAVASCRIPT]() {
        const js = await import("@shikijs/langs/javascript");

        return js.default[0];
    },
    async [Language.TYPESCRIPT]() {
        const ts = await import("@shikijs/langs/typescript");

        return ts.default[0];
    },
    async [Language.TYPESCRIPT_REACT]() {
        const tsx = await import("@shikijs/langs/tsx");

        return tsx.default[0];
    },
    async [Language.JAVASCRIPT_REACT]() {
        const jsx = await import("@shikijs/langs/jsx");

        return jsx.default[0];
    },
    async [Language.HTML]() {
        const html = await import("@shikijs/langs/html");

        return html.default.at(-1)!;
    },
    async [Language.CSS]() {
        const css = await import("@shikijs/langs/css");

        return css.default[0];
    },
    [Language.PLAINTEXT]: null,
    [Language.UNKNOWN]: null,
};

const languagesWithGrammars = new Set(Object.entries(grammars)
    .filter(([, loader]) => loader !== null)
    .map(([lang]) => lang as Language));

const repoRoot = resolve(import.meta.dirname, "..", "..");
const textmateDir = resolve(repoRoot, "src", "utils", "textmate");
const genDir = resolve(textmateDir, "grammars", "generated");
const langs = languagesWithGrammars;
const typeFile = "types.ts";

const typeFileContent = dedent`
    /* eslint-disable */
    // This file is generated. Do not edit.

    import * as shiki from "shiki";

    export type LazyLang = shiki.LanguageRegistration;
`;

await mkdir(genDir, { recursive: true });

await writeFile(resolve(genDir, typeFile), typeFileContent);

const output = [
    dedent`
        /* eslint-disable */
        // This file is generated by scripts/codegen/grammars.ts. Do not edit.

        import type { LazyLang } from "./${typeFile}";

        export type { LazyLang };

        import type { Language } from "@/utils/textmate/language";

        // enum cast, the values are only ever generated from the same enum
        export const languagesWithGrammars: Set<Language> = new Set(${JSON.stringify(Array.from(languagesWithGrammars.values()))} as Language[]);
    `,
];

for (const lang of langs) {
    const def = await grammars[lang]!();

    const content = dedent`
        /* eslint-disable */
        // This file is generated by scripts/codegen/grammars.ts. Do not edit.

        import type { LazyLang } from "./${typeFile}";
        const lang: LazyLang = /* @__PURE__ */ JSON.parse(${JSON.stringify(JSON.stringify(def))});
        export default lang;
    `;

    const fileName = `${languageDisplayNames[lang]}.ts`;
    const [ident] = lang.match(/[^.]+$/)!;

    await writeFile(resolve(genDir, fileName), content);

    output.push(`export function ${ident}(): Promise<LazyLang> { return import("./${fileName}").then(({default: d}) => d); }`);
}

const outputContent = output.join("\n");

await writeFile(resolve(genDir, "index.ts"), outputContent);
