import { dedent } from "@/utils/string";
import { TextmateTheme } from "@/utils/textmate/theme";
import { lazyLoadTextmateTheme } from "@/utils/textmate/themes";

import type * as monaco from "monaco-editor";
import { mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import type { ThemeRegistration } from "shiki";

// from monaco-vscode-textmate-theme-converter
function convertTheme(vscodeTheme: ThemeRegistration): monaco.editor.IStandaloneThemeData {
    const monacoThemeRule: monaco.editor.ITokenThemeRule[] = [];

    const returnTheme: monaco.editor.IStandaloneThemeData = {
        inherit: false,
        base: "vs-dark",
        colors: vscodeTheme.colors ?? {},
        rules: monacoThemeRule,
        encodedTokensColors: [],
    };

    for (const color of vscodeTheme.tokenColors ?? []) {
        if (typeof color.scope === "string") {
            const split = color.scope.split(",");

            if (split.length > 1) {
                // @ts-expect-error copied from other code and it works
                evalAsArray(color.scope = split);
                continue;
            }


            monacoThemeRule.push({
                ...color.settings, // token: color.scope.replace(/\s/g, '')
                token: color.scope,
            });
            continue;
        }

        if (Array.isArray(color.scope)) {
            evalAsArray(color.scope);
        }

        function evalAsArray(scopes: string[]) {
            for (const scope of scopes) {
                monacoThemeRule.push({
                    ...color.settings,
                    token: scope,
                });
            }
        }
    }

    return returnTheme;
}

const rootPath = resolve(import.meta.dirname, "..", "..");
const genPath = resolve(rootPath, "src", "components", "CodeEditor", "Monaco", "themes", "generated");

await mkdir(genPath, { recursive: true });

const typeFile = "types.ts";
const typeFilePath = resolve(genPath, typeFile);

const typeFileContent = dedent`
    /* eslint-disable */
    // This file is generated by scripts/codegen/monacoThemes.ts. Do not edit.

    import type * as monaco from "monaco-editor";

    export type MonacoThemeData = monaco.editor.IStandaloneThemeData;
`;

await writeFile(typeFilePath, `${typeFileContent}\n`);

const ret = [
    dedent`
        /* eslint-disable */
        // This file is generated by scripts/codegen/monacoThemes.ts. Do not edit.

        import { type MonacoThemeData } from "./${typeFile}";

        import { TextmateTheme } from "@/utils/textmate/theme";

        export { type MonacoThemeData };
    `,
];

const themes = Object.values(TextmateTheme).filter((v) => typeof v !== "number") as (keyof typeof TextmateTheme)[];
const themeValues = themes.map((t) => TextmateTheme[t]);

for (const theme of themes) {
    const tmTheme = await lazyLoadTextmateTheme(TextmateTheme[theme]);
    const monacoTheme = convertTheme(tmTheme);

    const content = dedent`
        /* eslint-disable */
        // This file is generated. Do not edit.
        import { type MonacoThemeData } from "./${typeFile}";

        const theme: MonacoThemeData = JSON.parse(${JSON.stringify(JSON.stringify(monacoTheme))});
        export default theme;
    `;

    const themeDisplayName = theme.toLowerCase();
    const themeFile = `${themeDisplayName}.ts`;
    const themeFilePath = resolve(genPath, themeFile);

    await writeFile(themeFilePath, `${content}\n`);

    ret.push(`export function ${theme}() { return import("./${themeFile}").then(({default: d}) => d) }`);
}

ret.push(dedent`
    export const loaderMap: Record<TextmateTheme, () => Promise<MonacoThemeData>> = {
        ${
            themeValues
                .map((v) => {
                    return `[${v}]: ${TextmateTheme[v]},`;
                })
                .join("\n")
        }
    };
`);

const content = ret.join("\n");

await writeFile(resolve(genPath, "index.ts"), `${content}\n`);
